### ISSUE TITLE
Can not use singularity

### ISSUE THREAD

**Issue by wangziyuan66** [novoalab/m6ABasecaller#4]
Hi,

My singularity version is apptainer version 1.2.4-1.el7.

I want to use singularity to run all the code but failed.

I used the second method.

FATAL:   stat my/path/modPhred/run: no such file or directory

**Comment by enovoa** [comment]
Hi @wangziyuan66 Could you try changing /my/path/modPhred/run to whatever PATH you have installed ModPhred at? Thanks!

**Comment by enovoa** [comment]
Hi @wangziyuan66 , Was your problem solved? Thanks

**Comment by wangziyuan66** [comment]
Well solved! Thanks a lot!

Eva Novoa ***@***.***> 于2024年1月6日周六 06:10写道：

**Comment by haotianteng** [comment]
Hi, I have encountered the same error. Could you elaborate more on how do you solve that?
I make sure the path is right but still encounter this error.

**Comment by enovoa** [comment]
Hi @haotianteng - Can you please show your error message and what command you are running? Thanks!

**Comment by haotianteng** [comment]
Hi @enovoa 
The error message is the same: FATAL: stat my/path/modPhred/run: no such file or directory

I managed to solve it by using the ```--bind``` command, however, I encountered another error (raised an issue here: https://github.com/novoalab/m6ABasecaller/issues/9#issue-2382603522), here is the full log:

```bash
singularity exec --nv --bind /data:/data --bind /home/haotiant:/home/haotiant modphred-3.6.1.simg modPhred/run -c ont-guppy/data/rna_r9.4.1_70bps_m6A_hac.cfg --host soft/ont-guppy/bin/guppy_basecall_server -f /data/HEK293T_RNA004/Homo_sapiens.GRCh38.cdna.ncrna.fa -o /data/HEK293T/test/ -i /home/haotiant/bridge_scratch/HEK293T/HEK293T-WT-rep1/fast5s/
WARNING: Not mounting requested bind point (already mounted in container): /home/haotiant
[2024-07-01 07:37:37] ===== Welcome, welcome to modPhred pipeline! =====
[2024-07-01 07:37:37] Connecting to: soft/ont-guppy/bin/guppy_basecall_server:5555 ... [mem:   150 MB]
[2024-07-01 07:37:37] Encoding modification info from 1 directories... [mem:   150 MB]
[2024-07-01 07:37:37]  /home/haotiant/bridge_scratch/HEK293T/HEK293T-WT-rep1/fast5s/ with 261 Fast5 file(s)... [mem:   150 MB]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniforge3/envs/python3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/haotiant/Tools/modPhred/modPhred/src/guppy_encode_live.py", line 105, in basecalling_worker
    client = GuppyClientBase(config_name=config, host=host, port=port, **kwargs)
  File "/opt/miniforge3/envs/python3.7/lib/python3.7/site-packages/pyguppyclient/client.py", line 35, in __init__
    self.socket.connect("tcp://%s:%s" % (host, port))
  File "zmq/backend/cython/socket.pyx", line 580, in zmq.backend.cython.socket.Socket.connect
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Invalid argument
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "modPhred/run", line 507, in <module>
    main()
  File "modPhred/run", line 436, in main
    o.MaxModsPerBase, o.recursive)
  File "/home/haotiant/Tools/modPhred/modPhred/src/guppy_encode_live.py", line 228, in mod_encode
    for ii, (fn, ofn, reads) in enumerate(p.imap(basecalling_worker, args), 1):
  File "/opt/miniforge3/envs/python3.7/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
zmq.error.ZMQError: Invalid argument
```

**Comment by enovoa** [comment]
HI @haotianteng you seem to use " my/path/modPhred/run" can you actually change "my/path" for whatever is your path? thanks

**Comment by haotianteng** [comment]
The path problem has solved, the error I encounter now is invalid argument mentioned above. 

I suspect it's because the version of Guppy in the singularity image, e.g. docker://lpryszcz/modphred-3.6.1 is too high and didn't accept --fast5_out argument. Can you have a check of the Guppy version installed in that docker image?

**Comment by enovoa** [comment]
hi @haotianteng i dont think its the guppy version because that's how we have used it in the past as well for many projects (for example, the bioRxiv preprint of the m6ABasecaller, see methods section). So I suspect it is something else. I am tagging @lpryszcz here in case he has any suggestions
