### ISSUE TITLE
FileNotFoundError: [Errno 2] could not open alignment file `./workspace.bam`: No such file or directory

### ISSUE THREAD

**Issue by vetmohit89** [novoalab/m6ABasecaller#6]
~/src/modPhred/run -f ./reference_genome_files/GRCh38.p13.genome.fa -o ./combined_sh33/ -i ./workspace/
[2024-02-22 14:41:06] ===== Welcome, welcome to modPhred pipeline! =====
[2024-02-22 14:41:06] Output directory exits. Steps completed previously will be skipped! [mem:   115 MB]
[2024-02-22 14:41:06] Encoding modification info from 1 directories... [mem:   115 MB]
[2024-02-22 14:41:06]  /data/user/mbansal/Fast5/BE2C_FAST5/combined_sh33/workspace/ with 383 Fast5 file(s)... [mem:   115 MB]
[2024-02-22 14:41:30]   RNA alphabet with 1 modification(s) {'A': ['Y'], 'C': [], 'G': [], 'U': []}. symbol2modbase: {'Y': 'm6A'}
[2024-02-22 15:16:53]   1,493,502,839 bases saved in FastQ, of those: 307,282 m6A [ 0.021%]   
[2024-02-22 15:16:53] Aligning FastQ files from 1 directories... [mem:   372 MB]
[2024-02-22 15:16:53]   > /data/user/mbansal/Fast5/BE2C_FAST5/combined_sh33/minimap2/workspace.bam [mem:   372 MB]
[2024-02-22 15:16:53] Indexing bam file(s)... [mem:   372 MB]
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[2024-02-22 15:16:53] Reporting positions that are likely modified to ./combined_sh33/mod.gz ... [mem:   372 MB]
[2024-02-22 15:16:53]  Getting regions covered by at least 25 reads... [mem:   372 MB]
[E::hts_open_format] Failed to open file "./minimap2/workspace.bam" : No such file or directory
Traceback (most recent call last):
  File "/home/mbansal/src/modPhred/run", line 507, in <module>
    main()
  File "/home/mbansal/src/modPhred/run", line 471, in main
    o.chr, o.step, logger=logger)
  File "/home/mbansal/src/modPhred/run", line 314, in mod_report
    chrs=chrs, step=step)
  File "/home/mbansal/src/modPhred/run", line 262, in get_covered_regions_per_bam
    sams = [pysam.AlignmentFile(b) for b in bams]
  File "/home/mbansal/src/modPhred/run", line 262, in <listcomp>
    sams = [pysam.AlignmentFile(b) for b in bams]
  File "pysam/libcalignmentfile.pyx", line 748, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 947, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `./combined_sh33/minimap2/workspace.bam`: No such file or directory

I have checked in mimimap2 is present in my conda modPhred env. I am not sure why it did not genrate the bam file.

When I used ~/src/modPhred/src/guppy_align.py it is giving error:

Traceback (most recent call last):
  File "/home/mbansal/src/modPhred/src/guppy_align.py", line 151, in <module>
    main()
  File "/home/mbansal/src/modPhred/src/guppy_align.py", line 146, in main
    o.unspliced)
  File "/home/mbansal/src/modPhred/src/guppy_align.py", line 74, in mod_align
    spliced = is_rna(indir) & (not unspliced)
  File "/data/user/home/mbansal/src/modPhred/src/guppy_encode.py", line 139, in is_rna
    if "U" in data["alphabet"]:
KeyError: 'alphabet'. 

Guppy version:
guppy_basecaller -v
: Guppy Basecalling Software, (C) Oxford Nanopore Technologies, Limited. Version 3.2.4+d9ed22f

**Comment by enovoa** [comment]
hi @vetmohit89 looking at your error above it seems that you have a missing library that samtools is requiring. 
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by enovoa** [comment]
We are planning to release modPhred as part of an upgrade of MasterOfPores, so hopefully if you are unable to sort the issue, it should be sorted out once we release the version 3 of [MasterOfPores](https://github.com/biocorecrg/MOP2). Once this is done, we will update the README accordingly. Thanks!

**Comment by lpryszcz** [comment]
Hi, indeed, this is related to samtools error, not modPhred. closing it.
